name: chatsy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pinput: ^5.0.1
  get: ^4.7.2
  flutter_markdown: ^0.7.4+1
  google_generative_ai: ^0.4.6
  share_plus:
  fluttertoast: ^8.2.2
  crypto: ^3.0.3
  intl:
  popover:
  responsive_sizer: ^3.1.1
  uuid:
  appsflyer_sdk: ^6.14.3
  youtube_explode_dart: ^2.2.1
  flutter_slidable: ^4.0.0
  dio: ^5.3.0
  gif_view: ^1.0.2
  flutter_secure_storage: ^9.0.0
  text_scroll: ^0.2.0
  square_progress_indicator: ^0.0.7
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0
  flutter_easyloading: ^3.0.5
  url_launcher:
  path: ^1.8.3
  in_app_purchase: ^3.1.7
  flutter_inapp_purchase: ^5.3.1
  webview_flutter: ^4.2.2
  image_cropper: ^9.1.0
  device_info_plus:
  camera: ^0.11.0+2
  flutter_localization: ^0.3.2
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  in_app_review: ^2.0.8
  cached_network_image: ^3.3.0
  shimmer:
  dropdown_button2:
  read_pdf_text: ^0.3.0
  file_picker:
  image_picker: ^1.0.5
  docx_to_text: ^1.0.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  # pull_to_refresh: ^2.0.0
  permission_handler: ^12.0.0+1
  carousel_slider: ^5.0.0
  video_player:
  provider: ^6.1.1
  visibility_detector:
  universal_html: ^2.2.4
  flutter_tts: ^4.2.2
  avatar_glow: ^3.0.1
  speech_to_text: ^7.0.0
  favicon: ^1.1.2
  duckduckgo_search: ^0.1.3
  connectivity_plus: ^6.0.5
  openai_dart: ^0.4.3
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  flutter_local_notifications: ^19.1.0
  app_tracking_transparency: ^2.0.6+1
  just_audio: ^0.10.0
  tavily_dart: ^0.1.0+1
  app_links: ^6.4.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  google_mlkit_text_recognition: ^0.15.0
  gap: ^3.0.1
  easy_refresh: ^3.4.0
  path_provider: ^2.1.5
  get_storage: ^2.1.1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  onesignal_flutter: ^5.3.3
  package_info_plus: ^8.3.0
  appvestor_billing_stats: ^1.0.32
  encrypt: ^5.0.3
  # super_context_menu: ^0.9.1

# google_mlkit_text_recognition: ^0.15.0

dependency_overrides:
  in_app_purchase_storekit: 0.3.22+1

dev_dependencies:

  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/jsons/
    - assets/videos/
    - assets/svg/

  fonts:
    - family: appIcons
      fonts:
        - asset: assets/fonts/appIcons.ttf
    - family: Helvetica-Bold
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
    - family: Helvetica-Light
      fonts:
        - asset: assets/fonts/Helvetica-Light.ttf
    - family: Helvetica-Regular
      fonts:
        - asset: assets/fonts/Helvetica-Regular.ttf

    - family: Helvetica-Advanced-Method
      fonts:
        - asset: assets/fonts/Helvetica-Light.ttf
          weight: 300
        - asset: assets/fonts/Helvetica-Regular.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

    - family: sFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf

    - family: sFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf


    - family: neuePowerTrialText
      fonts:
        - asset: assets/fonts/NeuePowerTrial-Bold.otf


    - family: neuePowerTrialTextExtraBold
      fonts:
        - asset: assets/fonts/NeuePowerTrial-Heavy.otf