// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDf2cr_lqq4Y0sE3aLHj6HlQeuseCRJM',
    appId: '1:50566955447:android:3c01e936822367bcb56832',
    messagingSenderId: '50566955447',
    projectId: 'ai-chatsy-390411',
    storageBucket: 'ai-chatsy-390411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY5W8k7zrRig75Nwc92kKKDKY0f8USsCg',
    appId: '1:50566955447:ios:540d7e88f4a602c9b56832',
    messagingSenderId: '50566955447',
    projectId: 'ai-chatsy-390411',
    storageBucket: 'ai-chatsy-390411.firebasestorage.app',
    androidClientId: '50566955447-1pul6uh8jdggapf1d71kclhdmk6lphpi.apps.googleusercontent.com',
    iosClientId: '50566955447-hvcong6ledci8he7lsc3lcf6ujlnbkcd.apps.googleusercontent.com',
    iosBundleId: 'com.aichatsy.app',
  );

}